### ISSUE TITLE
Gruntfile config

### ISSUE THREAD

**Issue by kreativkombinat** [ade25/generator-diazotheme#1]
New generated Theme makes mistake by first grunt dist:
/Users/sd/static/eisglut-app/Gruntfile.js:253
                options: {<% if (!diazoTheme) { %>
                          ^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token <
Warning: Task "dist" not found. Use --force to continue.

**Comment by potzenheimer** [comment]
Sollte nun auch gefixt sein
